# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HVWCJVx_i5NlR1BkftRbdsXMWEMDtwwH
"""

import matplotlib.pyplot as plt
import numpy as np

x = np.array([4,9,2,14,7,19,20,13,11,17,33,23,43,41,15,8,27,31,28])
y = np.array([5,8,4,10,7,15,13,17,43,25,24,11,18,36,49,35,37,2,8])

mycolor=['blue']
size=[25]
plt.scatter(x,y,color= mycolor,s=size)

plt.show()

import matplotlib.pyplot as plt
import numpy as np


x = np.linspace(0, 10, 100)
y = np.sin(x)


plt.figure(figsize=(8, 6))
plt.plot(x, y, color='blue', linewidth=2, label='Sinus(x)')


plt.title('Sinus Funksiyasining Grafigi', fontsize=14)
plt.xlabel('X qiymatlari', fontsize=12)
plt.ylabel('Y qiymatlari', fontsize=12)


plt.grid(True)
plt.legend()


plt.show()