# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12xI9MN3LI_Q-1QtpN5udbm0ymqgi8Bx-
"""

import matplotlib.pyplot as plt
import numpy as np

x = np.array([0, 6])
y = np.array([0, 250])

plt.plot(x, y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array([5,2,6,8,16,9])
y = np.array([5,8,1,10,18,15])

plt.plot(x, y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np


y = np.array([5,8,4,10,7,15])

plt.plot(y,marker="_")
plt.show()

import matplotlib.pyplot as plt
import numpy as np


y = np.array([5,14,6,11,4,15])

plt.plot(y,'o:g')
plt.show()

import matplotlib.pyplot as plt
import numpy as np


y = np.array([5,8,4,10,7,15])

plt.plot(y,marker="o",ms=15,mec='r')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x1 = np.array([0,1,2,3])
y1 = np.array([5,8,4,10])
x2 = np.array([0,1,2,3])
y2 = np.array([6,2,7,11])

plt.plot(x1,y1,x2,y2)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array([4,9,2,14,7,19])
y = np.array([5,8,4,10,7,15])


plt.scatter(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array([4,9,2,14,7,19])
y = np.array([5,8,4,10,7,15])
plt.scatter(x,y,color='red')

x = np.array([3,10,2,12,7,15])
y = np.array([1,7,5,10,3,18])
plt.scatter(x,y,color='blue')

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array([4,9,2,14,7,19])
y = np.array([5,8,4,10,7,15])

mycolor=['red','blue','green','aqua','yellow','black']
plt.scatter(x,y,color= mycolor)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array([4,9,2,14,7,19])
y = np.array([5,8,4,10,7,15])

mycolor=['red','blue','green','aqua','yellow','black']
size=[14,3,27,15,9,20]
plt.scatter(x,y,color= mycolor,s=size)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array(['A','B','C','D'])
y = np.array([5,8,4,10])

plt.bar(x,y)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array(['A','B','C','D'])
y = np.array([5,8,4,10])

plt.barh(x,y)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array(['A','B','C','D'])
y = np.array([5,8,4,10])

plt.bar(x,y,width=0.1)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

y = np.array([5,8,4,10])

plt.pie(y)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

y = np.array([5,8,4,10])
mylabels = ["BANANA","APPLE","CHERRIES","DATES"]

plt.pie(y,labels= mylabels)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

y = np.array([5,10,25,14])
mylabels = ["BANANA","APPLE","CHERRIES","DATES"]

plt.pie(y,labels= mylabels,startangle=90)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

y = np.array([5,10,25,14])
mylabels = ["BANANA","APPLE","CHERRIES","DATES"]
myexplode = [0.2,0,0,0]

plt.pie(y,labels= mylabels,startangle=90,explode=myexplode)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

y = np.array([5,10,25,14])
mylabels = ["BANANA","APPLE","CHERRIES","DATES"]
myexplode = [0.2,0,0,0]

plt.pie(y,labels= mylabels,startangle=90,explode=myexplode,shadow=True)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

y = np.array([5,10,25,14])
mylabels = ["BANANA","APPLE","CHERRIES","DATES"]
mycolor = ["black","hotpink","b","#4CAF50"]
myexplode = [0.2,0,0,0]

plt.pie(y,labels= mylabels,startangle=90,explode=myexplode,colors= mycolor)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

y = np.array([5,10,25,14])
mylabels = ["BANANA","APPLE","CHERRIES","DATES"]

plt.pie(y,labels= mylabels)
plt.legend()

plt.show()